[tool.poetry]
name = "commandflow"
version = "0.1.0"
description = ""
authors = ["dwpeng <1732889554@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
